[build]
command = "npm install && npm run build"
# For Next.js projects using SSR with the Netlify Next.js plugin, publish is set to .next
publish = ".next"

[build.environment]
NODE_VERSION = "18"

[[plugins]]
package = "@netlify/plugin-nextjs"
